### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by Blaimi** [colinbut/github-self-hosted-runners-terraform-ec2#1]
Hi,
would you like to add a license to this project to make it reusable?

Thanks in advance :)

**Comment by colinbut** [comment]
Hi @Blaimi - Yes could do.

**Comment by Blaimi** [comment]
Ah, I see, you already wrote „It is left to any future reader/user/forker of this Repository to tailor it accordingly to their own needs.“ in the readme. Unfortunately this is not enough for european law because it doesn't know the concept of public domain. I need at least a CC0 or WTFPL to reuse this code. MIT, Apache 2, BSD-2 or BSD-3 would also do the trick :wink:

**Comment by colinbut** [comment]
@Blaimi - Feel free to submit a PR for your recommendation.
